apiVersion: v1
kind: Service
metadata:
  name: selenium-hub 
  labels:
    name: selenium-hub 
spec:
  ports:
  - port: 4444 
    targetPort: 4444 
    name: port0
  selector:
    name: selenium-hub
  # type: NodePort
  type: LoadBalancer
  sessionAffinity: None
